server:
  port: ${services.ports.gateway}

spring:
  application:
    name: gateway

  cloud:
    gateway:
      restricted-paths:
        - /api/v1/[a-zA-Z]+/internal/.*
      global-filter:
        - LoggingGlobalFilter
        - RestrictedPathFilter
      routes:
        - id: post-route
          uri: ${services.hosts.post}
          predicates:
            - Path=/api/v1/post/**
          filters:
            - RewritePath=/api/v1/post/(?<remaining>.*), /api/v1/post/${remaining}
        - id: user-route
          uri: ${services.hosts.user}
          predicates:
            - Path=/api/v1/user/**
          filters:
            - RewritePath=/api/v1/user/(?<remaining>.*), /api/v1/user/${remaining}
        - id: follow-route
          uri: ${services.hosts.user}
          predicates:
            - Path=/api/v1/follows/**
          filters:
            - RewritePath=/api/v1/follows/(?<remaining>.*), /api/v1/follows/${remaining}
        - id: comment-route
          uri: ${services.hosts.interaction}
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - RewritePath=/api/v1/comments/(?<remaining>.*), /api/v1/comments/${remaining}
        - id: reaction-route
          uri: ${services.hosts.interaction}
          predicates:
            - Path=/api/v1/reactions/**
          filters:
            - RewritePath=/api/v1/reactions/(?<remaining>.*), /api/v1/reactions/${remaining}
