server:
  port: ${services.ports.post}
spring:
  application:
    name: post

  datasource:
    url: jdbc:postgresql://localhost:5432/postly
    username: postgres
    password: root123

  jpa:
    properties:
      hibernate:
        default_schema: posts

    hibernate:
      ddl-auto: update

    show-sql: true
